config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sessions#new'

  resources 'sessions', only: [:new]
  post 'provider', to: "sessions#redirect_to_provider", as: "session_provider"
  get "session", to: "sessions#create"

  resources 'games', only: %i[create show update destroy]
  resources 'locations', only: %i[index show]
  resources 'actions', only: [:update]
  resources 'scores', only: [:index]
  resources 'high_scores', only: [:index]
end

app/views/shared/_clock.html.erb
<h1 class="text-xl font-bold" id="clock" data-controller="timer" data-timer-start-value="<%= current_game.started_at.to_i %>" data-timer-end-value="<%= current_game.ended_at.to_i %>" data-timer-penalties-value="<%= current_player.penalties %>"></h1>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
    <strong class="font-bold">Holy smokes!</strong>
    <span class="block sm:inline"><%= msg %></span>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
              <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
            </span>
  </div>
<% end %>

app/views/shared/_go_back.html.erb
<%= link_to "Go Back", locations_path, data: {"turbo-stream": true}, id: "back_button", class: (invisible ? "invisible " : "") + "bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded-lg hover:cursor-pointer transition duration-300 ease-in-out hover:bg-blue-700 transform hover:-translate-y-1 hover:shadow-lg" %>

app/views/shared/_log_in.html.erb
<% if !user_loged_in? %>
  <div class="flex flex-col items-center">
    <%= form_with url: session_provider_path, method: :post do %>
      <%= button_tag data: { turbo: false }, class: "flex items-center bg-green-700 hover:bg-green-700 text-white font-bold py-3 px-6 rounded-lg hover:cursor-pointer transition duration-300 ease-in-out hover:bg-green-700 transform hover:-translate-y-1 hover:shadow-lg" do %>
        <span>Sign in with Google</span>
      <% end %>
    <% end %>
    <p class="text-gray-500 text-xs mt-2">...and keep your progress.</p>
  </div>
<% end %>