config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sessions#new'

  resources 'sessions', only: [:new]
  post 'provider', to: "sessions#redirect_to_provider", as: "session_provider"
  get "session", to: "sessions#create"

  resources 'games', only: %i[create show update destroy]
  resources 'locations', only: %i[index show]
  resources 'actions', only: [:update]
  resources 'scores', only: [:index]
  resources 'high_scores', only: [:index]
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  belongs_to :game
  has_many :actions
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  def index
    @locations = current_game.locations
  end

  def show
    @location = Location.find(params[:id])
  end
end

app/helpers/locations_helper.rb
# frozen_string_literal: true

module LocationsHelper
end

app/views/locations/_location.html.erb
<% location.actions.order(:index).each do |action| %>
  <%= render partial: "actions/action", locals: { action: action } %>
<% end %>

app/views/locations/_locations.html.erb
<% locations.each_slice(2) do |pair| %>
  <%  pair.each do |location| %>
    <%= link_to trans("locations.#{location.index}.name"), location_path(location), data: {"turbo-stream": true }, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded-lg hover:cursor-pointer transition duration-300 ease-in-out hover:bg-blue-700 transform hover:-translate-y-1 hover:shadow-lg" %>
  <% end %>
<% end %>

app/views/locations/index.turbo_stream.erb
<%= turbo_stream.update "control_panel", partial: "locations/locations", locals: { locations: @locations } %>
<%= turbo_stream.replace "back_button", partial: "shared/go_back", locals: { invisible: true } %>

app/views/locations/show.turbo_stream.erb
<%= turbo_stream.update "control_panel", partial: "locations/location", locals: { location: @location } %>
<%= turbo_stream.replace "back_button", partial: "shared/go_back", locals: { invisible: false } %>